### ISSUE TITLE
tables

### ISSUE THREAD

**Issue by hvargasojeda** [quarto-journals/jasa#6]
The tables appear at the beginning of each page by default. Can I place them anywhere on a page?

**Comment by cderv** [comment]
Which tables are you referring too ? 

Our default template does not have what you described so I believe this is something specific to your content. 
https://quarto-journals.github.io/jasa/

Also if the issue appear with another latex format, it is probably something LaTeX related, probably with floating table or something. I mean not sure it is specific with JASA template, which this format is about. 

Anyhow, this issue / question requires more information to help us help you. 

Thank you

**Comment by nicholasjhorton** [comment]
I wonder if the following use of `fig-pos:` might be helpful to allow tables to be placed in other locations:

https://stackoverflow.com/questions/76138248/figure-placement-quarto-markdown-float-specifier

See also https://quarto.org/docs/authoring/figures.html#latex-figures

I concur that this isn't specific to the excellent template for the journals of the American Statistical Association.

**Comment by hvargasojeda** [comment]
> Which tables are you referring too ?
> 
> Our default template does not have what you described so I believe this is something specific to your content. https://quarto-journals.github.io/jasa/
> 
> Also if the issue appear with another latex format, it is probably something LaTeX related, probably with floating table or something. I mean not sure it is specific with JASA template, which this format is about.
> 
> Anyhow, this issue / question requires more information to help us help you.
> 
> Thank you

**Comment by hvargasojeda** [comment]
Hello, yes I'm using Jasa template, ok let me explain better, I made a ggplot graph in Jasa template, and when I render it aligns at the beginning of the page but does not respect the location within the text structure.
Thanks.

**Comment by nicholasjhorton** [comment]
Note that when you output to pdf, the figure and table location is handled by LaTeX, which has very particular and sophisticated approaches to layout. By default, the layout specifies that such figures are displayed at the top of a page. This can be changed (see the link I shared earlier) to "b"ottom, "p"age [full page], or "h"ere.
